/// An online icon pack — name + URLs for icon images mapped to package names.
class OnlineIconPack {
  final String id;
  final String name;
  final String author;
  final String description;
  final Map<String, String> iconUrls;

  const OnlineIconPack({
    required this.id,
    required this.name,
    required this.author,
    required this.description,
    required this.iconUrls,
  });

  int get iconCount => iconUrls.length;

  factory OnlineIconPack.fromJson(Map<String, dynamic> json) {
    return OnlineIconPack(
      id: json['id'] as String? ?? '',
      name: json['name'] as String? ?? '',
      author: json['author'] as String? ?? 'Unknown',
      description: json['description'] as String? ?? '',
      iconUrls: Map<String, String>.from(json['icons'] as Map? ?? {}),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'author': author,
        'description': description,
        'icons': iconUrls,
      };

  /// Curated icon packs with direct image URLs (free to use).
  static const List<OnlineIconPack> curated = [
    OnlineIconPack(
      id: 'neon_glow',
      name: 'Neon Glow',
      author: 'Theme Studio',
      description: 'Vibrant neon-style icons with glow effects',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/fluency/96/gmail.png',
        'com.google.android.apps.maps': 'https://img.icons8.com/fluency/96/google-maps.png',
        'com.whatsapp': 'https://img.icons8.com/fluency/96/whatsapp.png',
        'com.instagram.android': 'https://img.icons8.com/fluency/96/instagram.png',
        'com.twitter.android': 'https://img.icons8.com/fluency/96/twitter.png',
        'com.spotify.music': 'https://img.icons8.com/fluency/96/spotify.png',
        'com.google.android.youtube': 'https://img.icons8.com/fluency/96/youtube.png',
        'com.facebook.katana': 'https://img.icons8.com/fluency/96/facebook-new.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/fluency/96/google-photos.png',
        'com.google.android.calendar': 'https://img.icons8.com/fluency/96/google-calendar.png',
        'com.google.android.apps.docs': 'https://img.icons8.com/fluency/96/google-docs.png',
        'com.google.android.gmm': 'https://img.icons8.com/fluency/96/google-maps.png',
        'com.android.chrome': 'https://img.icons8.com/fluency/96/chrome.png',
        'com.google.android.dialer': 'https://img.icons8.com/fluency/96/phone.png',
        'com.google.android.contacts': 'https://img.icons8.com/fluency/96/contacts.png',
        'com.google.android.apps.messaging': 'https://img.icons8.com/fluency/96/sms.png',
        'com.google.android.calculator': 'https://img.icons8.com/fluency/96/calculator.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/fluency/96/clock.png',
        'com.google.android.apps.magazines': 'https://img.icons8.com/fluency/96/google-news.png',
        'com.google.android.apps.playbooks': 'https://img.icons8.com/fluency/96/google-play-books.png',
      },
    ),
    OnlineIconPack(
      id: 'pastel_dream',
      name: 'Pastel Dream',
      author: 'Theme Studio',
      description: 'Soft pastel-colored icons',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/dusk/96/gmail.png',
        'com.whatsapp': 'https://img.icons8.com/dusk/96/whatsapp.png',
        'com.instagram.android': 'https://img.icons8.com/dusk/96/instagram.png',
        'com.spotify.music': 'https://img.icons8.com/dusk/96/spotify.png',
        'com.google.android.youtube': 'https://img.icons8.com/dusk/96/youtube.png',
        'com.facebook.katana': 'https://img.icons8.com/dusk/96/facebook-new.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/dusk/96/google-photos.png',
        'com.google.android.calendar': 'https://img.icons8.com/dusk/96/google-calendar.png',
        'com.android.chrome': 'https://img.icons8.com/dusk/96/chrome.png',
        'com.google.android.dialer': 'https://img.icons8.com/dusk/96/phone.png',
        'com.google.android.contacts': 'https://img.icons8.com/dusk/96/contacts.png',
        'com.google.android.apps.messaging': 'https://img.icons8.com/dusk/96/sms.png',
        'com.google.android.calculator': 'https://img.icons8.com/dusk/96/calculator.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/dusk/96/clock.png',
        'com.google.android.apps.docs': 'https://img.icons8.com/dusk/96/google-docs.png',
      },
    ),
    OnlineIconPack(
      id: 'line_black',
      name: 'Line Black',
      author: 'Theme Studio',
      description: 'Clean line-art style icons on dark backgrounds',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/ios-filled/96/gmail.png',
        'com.whatsapp': 'https://img.icons8.com/ios-filled/96/whatsapp.png',
        'com.instagram.android': 'https://img.icons8.com/ios-filled/96/instagram.png',
        'com.spotify.music': 'https://img.icons8.com/ios-filled/96/spotify.png',
        'com.google.android.youtube': 'https://img.icons8.com/ios-filled/96/youtube.png',
        'com.facebook.katana': 'https://img.icons8.com/ios-filled/96/facebook-new.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/ios-filled/96/google-photos.png',
        'com.android.chrome': 'https://img.icons8.com/ios-filled/96/chrome.png',
        'com.google.android.dialer': 'https://img.icons8.com/ios-filled/96/phone.png',
        'com.google.android.contacts': 'https://img.icons8.com/ios-filled/96/contacts.png',
        'com.google.android.apps.messaging': 'https://img.icons8.com/ios-filled/96/sms.png',
        'com.google.android.calculator': 'https://img.icons8.com/ios-filled/96/calculator.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/ios-filled/96/clock.png',
      },
    ),
    OnlineIconPack(
      id: 'glass_morphism',
      name: 'Glass',
      author: 'Theme Studio',
      description: 'Frosted glass effect with blur depth',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/plasticine/100/gmail.png',
        'com.whatsapp': 'https://img.icons8.com/plasticine/100/whatsapp.png',
        'com.instagram.android': 'https://img.icons8.com/plasticine/100/instagram.png',
        'com.spotify.music': 'https://img.icons8.com/plasticine/100/spotify.png',
        'com.google.android.youtube': 'https://img.icons8.com/plasticine/100/youtube.png',
        'com.facebook.katana': 'https://img.icons8.com/plasticine/100/facebook-new.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/plasticine/100/google-photos.png',
        'com.google.android.calendar': 'https://img.icons8.com/plasticine/100/google-calendar.png',
        'com.android.chrome': 'https://img.icons8.com/plasticine/100/chrome.png',
        'com.google.android.dialer': 'https://img.icons8.com/plasticine/100/phone.png',
        'com.google.android.contacts': 'https://img.icons8.com/plasticine/100/contacts.png',
        'com.google.android.apps.messaging': 'https://img.icons8.com/plasticine/100/sms.png',
        'com.google.android.calculator': 'https://img.icons8.com/plasticine/100/calculator.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/plasticine/100/clock.png',
        'com.google.android.apps.docs': 'https://img.icons8.com/plasticine/100/google-docs.png',
      },
    ),
    OnlineIconPack(
      id: 'pixel_art',
      name: 'Pixel Art',
      author: 'Theme Studio',
      description: 'Retro 8-bit pixel art style icons',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/color/96/gmail.png',
        'com.whatsapp': 'https://img.icons8.com/color/96/whatsapp.png',
        'com.instagram.android': 'https://img.icons8.com/color/96/instagram.png',
        'com.spotify.music': 'https://img.icons8.com/color/96/spotify.png',
        'com.google.android.youtube': 'https://img.icons8.com/color/96/youtube.png',
        'com.facebook.katana': 'https://img.icons8.com/color/96/facebook-new.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/color/96/google-photos.png',
        'com.google.android.calendar': 'https://img.icons8.com/color/96/google-calendar.png',
        'com.android.chrome': 'https://img.icons8.com/color/96/chrome.png',
        'com.google.android.dialer': 'https://img.icons8.com/color/96/phone.png',
        'com.google.android.contacts': 'https://img.icons8.com/color/96/contacts.png',
        'com.google.android.apps.messaging': 'https://img.icons8.com/color/96/sms.png',
        'com.google.android.calculator': 'https://img.icons8.com/color/96/calculator.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/color/96/clock.png',
        'com.google.android.apps.docs': 'https://img.icons8.com/color/96/google-docs.png',
      },
    ),
    OnlineIconPack(
      id: 'watercolor',
      name: 'Watercolor',
      author: 'Theme Studio',
      description: 'Painted watercolor brush stroke icons',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/external-walkline-grass-walkline/96/external-gmail-email-walkline-grass.png',
        'com.whatsapp': 'https://img.icons8.com/external-kmg-design-grass-walkline/96/external-whatsapp-messaging-kmg-design-grass.png',
        'com.instagram.android': 'https://img.icons8.com/external-justicon-grass-walkline/96/external-instagram-social-media-justicon-grass.png',
        'com.spotify.music': 'https://img.icons8.com/external-those-icons-grass-walkline/96/external-spotify-music-those-icons-grass.png',
        'com.google.android.youtube': 'https://img.icons8.com/external-youtube-grass-walkline/96/external-youtube-social-media-youtube-grass.png',
        'com.facebook.katana': 'https://img.icons8.com/external-those-icons-grass-walkline/96/external-facebook-social-media-those-icons-grass.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/external-walkline-grass-walkline/96/external-google-photos-google-walkline-grass.png',
        'com.android.chrome': 'https://img.icons8.com/external-walkline-grass-walkline/96/external-chrome-browser-walkline-grass.png',
        'com.google.android.dialer': 'https://img.icons8.com/external-walkline-grass-walkline/96/external-phone-call-ui-walkline-grass.png',
        'com.google.android.calculator': 'https://img.icons8.com/external-walkline-grass-walkline/96/external-calculator-math-walkline-grass.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/external-walkline-grass-walkline/96/external-clock-time-walkline-grass.png',
        'com.google.android.calendar': 'https://img.icons8.com/external-walkline-grass-walkline/96/external-calendar-date-walkline-grass.png',
      },
    ),
    OnlineIconPack(
      id: 'gradient_mesh',
      name: 'Gradient',
      author: 'Theme Studio',
      description: 'Smooth colorful gradient icons',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/arcade/96/gmail.png',
        'com.whatsapp': 'https://img.icons8.com/arcade/96/whatsapp.png',
        'com.instagram.android': 'https://img.icons8.com/arcade/96/instagram.png',
        'com.spotify.music': 'https://img.icons8.com/arcade/96/spotify.png',
        'com.google.android.youtube': 'https://img.icons8.com/arcade/96/youtube.png',
        'com.facebook.katana': 'https://img.icons8.com/arcade/96/facebook-new.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/arcade/96/google-photos.png',
        'com.google.android.calendar': 'https://img.icons8.com/arcade/96/google-calendar.png',
        'com.android.chrome': 'https://img.icons8.com/arcade/96/chrome.png',
        'com.google.android.dialer': 'https://img.icons8.com/arcade/96/phone.png',
        'com.google.android.contacts': 'https://img.icons8.com/arcade/96/contacts.png',
        'com.google.android.apps.messaging': 'https://img.icons8.com/arcade/96/sms.png',
        'com.google.android.calculator': 'https://img.icons8.com/arcade/96/calculator.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/arcade/96/clock.png',
        'com.google.android.apps.docs': 'https://img.icons8.com/arcade/96/google-docs.png',
      },
    ),
    OnlineIconPack(
      id: 'outline_mono',
      name: 'Outline',
      author: 'Theme Studio',
      description: 'Minimal monochrome outline icons',
      iconUrls: {
        'com.google.android.gm': 'https://img.icons8.com/ios-glyphs/96/gmail.png',
        'com.whatsapp': 'https://img.icons8.com/ios-glyphs/96/whatsapp.png',
        'com.instagram.android': 'https://img.icons8.com/ios-glyphs/96/instagram.png',
        'com.spotify.music': 'https://img.icons8.com/ios-glyphs/96/spotify.png',
        'com.google.android.youtube': 'https://img.icons8.com/ios-glyphs/96/youtube.png',
        'com.facebook.katana': 'https://img.icons8.com/ios-glyphs/96/facebook-new.png',
        'com.google.android.apps.photos': 'https://img.icons8.com/ios-glyphs/96/google-photos.png',
        'com.android.chrome': 'https://img.icons8.com/ios-glyphs/96/chrome.png',
        'com.google.android.dialer': 'https://img.icons8.com/ios-glyphs/96/phone.png',
        'com.google.android.contacts': 'https://img.icons8.com/ios-glyphs/96/contacts.png',
        'com.google.android.apps.messaging': 'https://img.icons8.com/ios-glyphs/96/sms.png',
        'com.google.android.calculator': 'https://img.icons8.com/ios-glyphs/96/calculator.png',
        'com.google.android.apps.clock': 'https://img.icons8.com/ios-glyphs/96/clock.png',
      },
    ),
  ];
}
